workflows:
  ios-build:
    name: StockBarcodeReader iOS Build
    environment:
      groups:
        - ios_signing
      vars:
        XCODE_WORKSPACE: "stockbarcodereader.xcodeproj"
        XCODE_SCHEME: "stockbarcodereader"
        BUNDLE_ID: "com.ananapp.stockbarcodereader"
        APP_STORE_CONNECT_TEAM_ID: "YOUR_TEAM_ID_HERE"
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Install CocoaPods dependencies
        script: |
          pod install || echo "No Pods to install"
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --export-method app-store \
            --archive-flags="-allowProvisioningUpdates"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key:
          key_id: $APP_STORE_CONNECT_KEY_ID
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          private_key: $APP_STORE_CONNECT_PRIVATE_KEY
